### ISSUE TITLE
可以提供恶意jar包的构造方式么

### ISSUE THREAD

**Issue by hatnoop** [Wileysec/nacos_derby_rce#1]
有需求注入哥斯拉、suo5等内存马，可以分享下jar包的构造方式么

**Comment by Wileysec** [comment]
> 有需求注入哥斯拉、suo5等内存马，可以分享下jar包的构造方式么

可以自定义脚本，生成一个哥斯拉或者suo5内存马转十六进制写到代码里，这里没有用到远程加载jar包，有时间更新，谢谢关注！

**Comment by Wileysec** [comment]
> 有需求注入哥斯拉、suo5等内存马，可以分享下jar包的构造方式么

生成了一下哥斯拉和suo5内存马，生成出来字节码过大，插入数据库一直报错内容过大，冰蝎马的字节码刚刚好，只能先注入冰蝎马再想办法注入其他内存马，感谢关注！

**Comment by Wileysec** [comment]
> 有需求注入哥斯拉、suo5等内存马，可以分享下jar包的构造方式么

生成了一下哥斯拉和suo5内存马，生成出来字节码过大，插入数据库一直报错内容过大，冰蝎马的字节码刚刚好，只能先注入冰蝎马再想办法注入其他内存马，感谢关注！

**Comment by Conan924** [comment]
你好像是copy我的吧 哥们
